spring.application.name=Order-Service
server.port=8083


#PostgreSql
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true


# liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml


user-service.base-url=${USER_SERVICE_BASE_URL:http://user-service:8080/api/users}





spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

# producer -> JSON ??? type headers
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=true

# consumer <- JSON ??? type headers, ??? ?????? ??????
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.group-id=order-service
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.innowise.OrderService.kafka.event.CreatePaymentEvent
spring.kafka.consumer.auto-offset-reset=earliest

# topics
app.kafka.topics.create-order=create-order
app.kafka.topics.create-payment=create-payment



management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true



# RESILIENCE4J - CIRCUIT BREAKER

resilience4j.circuitbreaker.instances.userService.slidingWindowSize=15
resilience4j.circuitbreaker.instances.userService.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.userService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.userService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.userService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.userService.automaticTransitionFromOpenToHalfOpenEnabled=true
logging.level.io.github.resilience4j.circuitbreaker=DEBUG

# RESILIENCE4J - TIME LIMITER

resilience4j.timelimiter.instances.userService.timeoutDuration=3s