name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build & Test (Maven)
        run: mvn -B clean verify

      - name: Build Docker image
        run: docker build -t order-service:${{ github.sha }} .

      - name: Save Docker image to file
        run: |
          docker save order-service:${{ github.sha }} | gzip > order-service-${{ github.sha }}.tar.gz

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: order-service-image
          path: order-service-${{ github.sha }}.tar.gz
